<?php
define('MODULE_NESTEDCHECKBOXSETFIELD_PATH', rtrim(dirname(__FILE__), DIRECTORY_SEPARATOR));

$folders = explode(DIRECTORY_SEPARATOR, MODULE_NESTEDCHECKBOXSETFIELD_PATH);
define('MODULE_NESTEDCHECKBOXSETFIELD_DIR', rtrim(array_pop($folders), DIRECTORY_SEPARATOR));
unset($folders);